{% set version = "3.1.3" %}

package:
  name: pyparsing
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyparsing/pyparsing-{{ version }}.tar.gz
  sha256: 5d549d2a1b5e1c3e952bb55ea247bfb5ad427ea307566a350db2b3c34d4ce181

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - flit-core
  run:
    - python >=3.6

test:
  imports:
    - pyparsing
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pyparsing.wikispaces.com/
  license: MIT
  license_file: LICENSE
  summary: Create and execute simple grammars
  description: |
    The pyparsing module is an alternative approach to creating and executing
    simple grammars, vs. the traditional lex/yacc approach, or the use of
    regular expressions. The pyparsing module provides a library of classes
    that client code uses to construct the grammar directly in Python code.
  doc_url: http://pyparsing.wikispaces.com/Documentation
  dev_url: https://svn.code.sf.net/p/pyparsing/code/

extra:
  recipe-maintainers:
    - thewchan
    - msarahan
    - ocefpaf
    - jan-janssen
