{% set name = "pyparsing" %}
{% set version = "1.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyparsing-{{ version }}.tar.gz
  sha256: 5c84aa4500e82d5aa2c0842d5628c5da985e68ac1fb33554e0e5547eb3c85a75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - python >=3.0

test:
  imports:
    - pyparsing
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pyparsing.wikispaces.com/
  summary: Python parsing module
  doc_url: https://pythonhosted.org/pyparsing/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
