{% set version = "3.0.1" %}

package:
  name: pyparsing
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyparsing/pyparsing-{{ version }}.tar.gz
  sha256: 84196357aa3566d64ad123d7a3c67b0e597a115c4934b097580e5ce220b91531

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - pyparsing
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://pyparsing.wikispaces.com/
  license: MIT
  license_file: LICENSE
  summary: Create and execute simple grammars
  description: |
    The pyparsing module is an alternative approach to creating and executing
    simple grammars, vs. the traditional lex/yacc approach, or the use of
    regular expressions. The pyparsing module provides a library of classes
    that client code uses to construct the grammar directly in Python code.
  doc_url: http://pyparsing.wikispaces.com/Documentation
  dev_url: https://svn.code.sf.net/p/pyparsing/code/

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - jan-janssen
