travis:
  secure:
    BINSTAR_TOKEN: KHqSAJTVHlU5uDCxWypDz6fKoYRQCrszMVF2xy6tQfjJLhKwyp9VSa4e9CGF6mz9nBAHziCLncG6rwjb8W9A205nnqxJW8R65y3rNTPI2MuJBbdRKebRvBx51BwBvq6V8Y6Z781sHJ4/We8kWedhfbJhxharvg6tI8EquxcnLj/X6Uwgdr5WvFmYjTtaLWOA8ppLnVG5VdOerR0JzbpoHx9chwm3IWveEweM01XFGE07TxA2c8vAgDQ9Lojnz+PkoNU3e4NMAXbvKen67hCGoFQCxun/a4I8xxQm1SoC4ZsyiiIQoTxjpSrJ81AZhyOnSftimBkZ+/Jg5YgCAw9ENLcOQ8/tu7SA2X9iv9wHuI4MheYR/BwN9s71m8kzNGWZFIy+DzB2Dadj5s/aZJb5gHUe/pJinHmhtGjgq1WZRxTMLrITOHI5J9f5w/BtSZ22tHZwA+tPQ6JIoJLCVJhXqlu6gPL4Dlmt+3nZsaicXnorAuzlSPg1tjxJ/QOXia79lFD+a0J9QLV1gR/VUPaGUZ3DhwHyFFFgssHT6mxcB4IopnGNlqjT0rMAoOEydCy/CUcPYq8hTzSRQCtMRydsEP9833nMInszFvpKYO13HCNZ5DB1fEHFZ466UPKljFPvnI6a0qjoBBd5tonEkAlYear7Sofa9VRUcYghISIbu0k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
